### PR TITLE
Add a note about unsetting baseurl

### PR DESCRIPTION
**Pull request by kostajh**
This addresses the comment in #14

### CODE REVIEW

**Comment by tristen** [comment]
Why do you need to unset it? `localhost:4000/starter/` works just fine and the baseurl variable is helpful for moving a project around parts of a url.

**Comment by kostajh** [comment]
Ahh... of course! Well, maybe it would be better to clarify that you need to visit `http://localhost:4000/starter` in the README. It's obvious now, but it took me a while to figure out why `http://localhost:4000` was not displaying any data.

**Comment by tristen** [comment]
Yeah, good point on documenting this. Happy to pull in a pr for that text!

**Comment by kostajh** [comment]
Done in 09df9c2, feel free to reword as you like. Thanks!

**Comment by tristen** [comment]
Thanks!

**Pull request merged**
